from fastapi import FastAPI, HTTPException, File, UploadFile, Form, Depends
from app.schemas import PostCreate, PostResponse, UserRead, UserCreate, UserUpdate
from app.db import Post, create_db_and_tables, get_async_session, User

from sqlalchemy.ext.asyncio import AsyncSession
from contextlib import asynccontextmanager
from sqlalchemy import select
from app.images import imagekit
from imagekitio.models.UploadFileRequestOptions import UploadFileRequestOptions
import shutil
import os
import uuid
import tempfile

from app.users import auth_backend, current_active_user, fastapi_users 

from typing import List

# from sqlalchemy.orm import joinedload

@asynccontextmanager
async def lifespan(app: FastAPI):
    await create_db_and_tables()
    yield

app = FastAPI(lifespan=lifespan)

app.include_router(fastapi_users.get_auth_router(auth_backend), prefix="/auth/jwt", tags=["auth"])
app.include_router(fastapi_users.get_register_router(UserRead, UserCreate), prefix="/auth", tags=["auth"])
app.include_router(fastapi_users.get_reset_password_router(), prefix="/auth", tags=["auth"])
app.include_router(fastapi_users.get_verify_router(UserRead), prefix="/auth", tags=["auth"])
app.include_router(fastapi_users.get_users_router(UserRead, UserUpdate), prefix="/users", tags=["users"])


@app.post("/upload")

async def upload_file(
    file: UploadFile = File(...),
    caption: str = Form(...),
    user: User = Depends(current_active_user),
    session: AsyncSession = Depends(get_async_session)
):  
    temp_file_path = None

    try: 
        # Save the uploaded file to a temporary location
        suffix = os.path.splitext(file.filename)[1]
        with tempfile.NamedTemporaryFile(delete=False, suffix=suffix) as temp_file:
            temp_file_path = temp_file.name
            shutil.copyfileobj(file.file, temp_file)

        # Upload the file to ImageKit
        upload_result = imagekit.upload_file(
            file=open(temp_file_path, 'rb'),
            file_name=file.filename,
            options=UploadFileRequestOptions(
                use_unique_file_name=True,
                tags= ["backend_upload"]
            )
        )
        if upload_result.response_metadata.http_status_code == 200:
            
            # Save post details to the database
            post = Post(
                user_id= user.id,
                caption=caption,
                url= upload_result.url,
                file_type= "video" if file.content_type.startswith("video/") else "image",
                file_name= upload_result.name
            )
            # Add, commit and refresh to get the ID and other autogenerated fields
            session.add(post)
            await session.commit()
            await session.refresh(post)
            return post
        
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
    finally:
        # Clean up the temporary file
        if temp_file_path and os.path.exists(temp_file_path):
            os.unlink(temp_file_path)
        file.file.close()

@app.get("/feed")
async def get_feed(
    user: User = Depends(current_active_user),
    session: AsyncSession = Depends(get_async_session)
):
    # Fetch all posts (simple query, no relationships)
    result = await session.execute(select(Post).order_by(Post.created_at.desc()))
    posts = result.scalars().all()  # List of Post objects

    # Fetch all users once and map to a dict for quick lookup (your commented code!)
    user_result = await session.execute(select(User))
    users = user_result.scalars().all()
    user_dict = {u.id: u.email for u in users}  # {UUID: email}

    posts_data = []
    for post in posts:
        # Safe lookup: .get() defaults to "Unknown" if user_id missing (edge case)
        post_email = user_dict.get(post.user_id, "Unknown")
        
        posts_data.append({
            "id": str(post.id),
            "user_id": str(post.user_id),
            "caption": post.caption,
            "url": post.url,
            "file_type": post.file_type,
            "file_name": post.file_name,
            "created_at": post.created_at.isoformat(),
            "is_owner": post.user_id == user.id,
            "email": post_email  # Now 100% safe—no post.user needed
        })
    return posts_data



@app.delete("/post/{post_id}")
async def delete_post(
    post_id: str,
    user: User = Depends(current_active_user),
    session: AsyncSession = Depends(get_async_session)
):  
    try:
        result = await session.execute(
            select(Post).where(Post.id == uuid.UUID(post_id))
        )
        post = result.scalars().first()

        if not post: 
            raise HTTPException(status_code=404, detail="Post not found")
        
        if post.user_id != user.id:
            raise HTTPException(status_code=403, detail="Not authorized to delete this post")
        
        await session.delete(post)
        await session.commit()
        return {"detail": "Post deleted successfully"}
    
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


    